### ISSUE TITLE
RuntimeError: JupyterLab failed to build

### ISSUE THREAD

**Issue by javidsch** [jupyterlab/jupyterlab-github#97]
It works on Windows 10/Anaconda(version=2019.10).

I've tried on AWS/Linux EC2, there was an issue.
Tested in two cases: on JupyterHub and on Jupyter notebok - the same result!
One point, I did it when JupyterHub and Jupyter was runnning, after failed I stooped and tried again - the same result!

**Run command:**
(base) []$ jupyter labextension install @jupyterlab/github
Building jupyterlab assets (build:prod:minimize)
An error occured.
RuntimeError: JupyterLab failed to build
See the log file for details:  /tmp/jupyterlab-debug-te2pdi6d.log

**From log file**
> node /home/ec2-user/anaconda3/lib/python3.7/site-packages/jupyterlab/staging/yarn.js yarn-deduplicate -s fewer
yarn run v1.15.2
$ /home/ec2-user/anaconda3/share/jupyter/lab/staging/node_modules/.bin/yarn-deduplicate -s fewer
Done in 1.02s.

> node /home/ec2-user/anaconda3/lib/python3.7/site-packages/jupyterlab/staging/yarn.js run build:prod:minimize
yarn run v1.15.2
$ cross-env NODE_OPTIONS=--max_old_space_size=4096 webpack --config webpack.prod.minimize.config.js
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

JupyterLab failed to build
Traceback (most recent call last):

  File "/home/ec2-user/anaconda3/lib/python3.7/site-packages/jupyterlab/debuglog.py", line 47, in debug_logging
    yield

  File "/home/ec2-user/anaconda3/lib/python3.7/site-packages/jupyterlab/labextensions.py", line 105, in start
    core_config=self.core_config)

  File "/home/ec2-user/anaconda3/lib/python3.7/site-packages/jupyterlab/commands.py", line 378, in build
    command=command, clean_staging=clean_staging)

  File "/home/ec2-user/anaconda3/lib/python3.7/site-packages/jupyterlab/commands.py", line 583, in build
    raise RuntimeError(msg)

RuntimeError: JupyterLab failed to build

Exiting application: jupyter

**Comment by javidsch** [comment]
And now jupyter lab try to build it... but fails...
https://imgur.com/a/lPZxCHC

**Comment by mripani** [comment]
Same issue 

First I had this one:

Unable to communicate with the jupyterlab-dash JupyterLab extension.
Is this Python kernel running inside JupyterLab with the jupyterlab-dash
extension installed?

You can install the extension with:

$ jupyter labextension install jupyterlab-dash

Then trying to re-install the package in a specif folder:

Building jupyterlab assets (build:prod:minimize)
An error occured.
RuntimeError: JupyterLab failed to build
See the log file for details:

**Comment by zerualem** [comment]
I am facing a similar issue when trying to install jupyterlab/toc

**Comment by foxjr** [comment]
Have you tried `jupyter labextension install --minimize=False <labextension>`?

**Comment by dhimmel** [comment]
> I am facing a similar issue when trying to install jupyterlab/toc

We hit a similar issue and @ravwojdyla figured out that it was due to node running out of memory by looking at the log. The solution was to increase the node memory limit like

```bash
NODE_OPTIONS=--max_old_space_size=4096 jupyter labextension install @jupyterlab/toc
```

Not sure if that helps.
